version: 2
updates:
  # Keeps npm dependencies up to date
  - package-ecosystem: "npm"
    open-pull-requests-limit: 10
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      include: scope
      prefix: chore

  # Keep GitHub Actions up to date
  - package-ecosystem: "github-actions"
    open-pull-requests-limit: 10
    directory: /
    schedule:
      interval: weekly
    commit-message:
      include: scope
      prefix: chore
