name: Integrate

on:
  push:
    paths-ignore:
      - "**.md"
    branches:
      - main
  pull_request:
    paths-ignore:
      - "**.md"
  workflow_dispatch:

jobs:
  format:
    name: Check format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up node
        uses: actions/setup-node@v3
        with:
          cache: npm
      - name: Install dependencies
        run: npm ci --ignore-scripts
      - name: Run Prettier
        run: npm run format -- --check

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up node
        uses: actions/setup-node@v3
        with:
          cache: npm
      - name: Install dependencies
        run: npm ci --ignore-scripts
      - name: Run ESLint
        run: npm run lint

  test:
    name: Test (${{ matrix.env }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        env: ["web", "node"]
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
      fail-fast: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up node
        uses: actions/setup-node@v3
        with:
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Build extension and tests
        run: npm run build
      - name: Run tests
        run: xvfb-run -a npm run test --env "${{ matrix.env }}"
        if: runner.os == 'Linux'
      - name: Run tests
        run: npm run test --env "${{ matrix.env }}"
        if: runner.os != 'Linux'
