name: Release

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Integrate"]
    branches: [main]
    types:
      - completed

jobs:
  release:
    if:
      ${{ github.event.workflow_run.conclusion == 'success' ||
      github.event.action == 'workflow_dispatch' }}
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.SEMANTIC_RELEASE_GIT_TOKEN }}
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm ci --ignore-scripts
      - name: Build extension
        run: npm run build -- --env production
      - name: Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
